# Generated by Django 6.0 on 2025-12-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_date_posted_alter_post_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='display_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
