# Generated by Django 6.0 on 2025-12-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
